
# os: osx

# osx_image: xcode11.2
dist: trusty

language: python

cache: pip

python:
  - "3.7"

# command to install dependencies
install:
  # - pip install -r requirements.txt
  pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# command to run tests
script: ${TRAVIS_BUILD_DIR}/runtests.sh
